version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis_container
    restart: always
    ports:
      - '6379:3679'
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: devcamper
    depends_on:
      - redis
    ports:
      - '3001:3001'

volumes:
  redis_data:
    driver: local
