name: Deploy to EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
        
            - name: Stop and remove existing containers
              run: |
                cd ~/DevCamper-API || mkdir -p DevCamper-API && cd DevCamper-API
                sudo docker-compose down || true
            
            - name: Pull latest changes
              run: |
                cd ~/DevCamper-API
                git pull origin main
            
            - name: Build and start containers
              run: |
                cd ~/DevCamper-API
                sudo docker-compose up --build -d
