name: Configure Nginx

on:
    push:
        branches:
            - main
    
jobs:
    deploy:
        runs-on: self-hosted
        
        env:
            DEPLOY_PATH: "/home/ubuntu/DevCamper-API"
            GH_PAT: ${{ secrets.GH_PAT }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            
            - name: Ensure Repository Exists
              run: |
                if [ ! -d "$DEPLOY_PATH" ]; then
                    git clone https://x-access-token:${GH_PAT}@github.com/SymonMuchemi/DevCamper-API.git $DEPLOY_PATH
                fi
            - name: Run config script
              run: |
                chmod +x ./DevCamper-API/nginx_setup_script.sh
                ./DevCamper-API/nginx_setup_script.sh
